WebUi/Models/CurrentResult.cs
namespace WebUi
{
    public class CurrentResult
    {
        public string ServiceTypeName { get; set; }
        public decimal VolumeOfServices { get; set; }
        public decimal Cost { get; set; }
        public decimal Normative { get; set; }
        public decimal Rate { get; set; }
        public string Units { get; set; }
        public decimal CommonCost { get; set; }
    }
}

WebUi/Models/ErrorViewModel.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;
using Shared;
using Microsoft.AspNetCore.Mvc;
namespace WebUi.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public string? ExceptionMessage { get; set; }
    }
}

WebUi/Models/Request/CalculateRequestData.cs
namespace WebUi
{
    public class CalculateRequestData
    {
        public decimal ColdWaterMeterValue { get; set; }
        public decimal ThermalEnergyMeterValue { get; set; }
        public decimal HeatCarrierMeterValue { get; set; }
        public decimal ElectroEnergyCommonMeterValue { get; set; }
        public decimal ElectroEnergyDayMeterValue { get; set; }
        public decimal ElectroEnergyNightMeterValue { get; set; }
        public int ResidentsCount { get; set; }

    }
}

WebUi/Models/RequestData.cs
using System.ComponentModel.DataAnnotations;

namespace WebUi
{
    public class RequestData
    {
        private const string messageReq = "Поле обязательно для заполнения";
        private const string messageRegExp = "Введите корректное значение";

        [Required(ErrorMessage = messageReq)]
        [RegularExpression("([.0-9]+)", ErrorMessage = messageRegExp)]
        public decimal ColdWaterMeterValues { get; set; }

        [Required(ErrorMessage = messageReq)]
        [RegularExpression("([.0-9]+)", ErrorMessage = messageRegExp)]
        public decimal HotWaterMeterValue { get; set; }

        [Required(ErrorMessage = messageReq)]
        [RegularExpression("([.0-9]+)", ErrorMessage = messageRegExp)]
        public decimal ElectroEnergyCommonMeterValue { get; set; }

        [Required(ErrorMessage = messageReq)]
        [RegularExpression("([.0-9]+)", ErrorMessage = messageRegExp)]
        public decimal ElectroEnergyDayMeterValue { get; set; }

        [Required(ErrorMessage = messageReq)]
        [RegularExpression("([.0-9]+)", ErrorMessage = messageRegExp)]
        public decimal ElectroEnergyNightMeterValue { get; set; }

        [Required(ErrorMessage = messageReq)]
        [RegularExpression("([.0-9]+)", ErrorMessage = messageRegExp)]
        [Range(1, int.MaxValue, ErrorMessage = "Значение должно быть не меньше 1")]
        public int ResidentsCount { get; set; } = 1;
    }
}

WebUi/Controllers/CalculateController.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Shared;
using System.Diagnostics;
using WebUi.Models;

namespace WebUi.Controllers
{
    public class CalculationController : Controller
    {
        private ICalculationService _calcService;
        public CalculationController(ICalculationService calcService)
        {
            _calcService = calcService;
        }
        public IActionResult PutValues()
        {
            var allServicesEmpty = new RequestData();
            return View(allServicesEmpty);
        }

        [HttpPost]
        public IActionResult CurrentResult(RequestData services)
        {
            if (services is null) return null;

            _calcService.PutRequest(services);
            var res = _calcService.CalculateGetResults();

            ViewBag.CommonCost = _calcService.GetCommonCost();

            return View(res);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            string errMessage;

            if (HttpContext.Features.Get<IExceptionHandlerPathFeature>()?.Error is CalculatorException)
                errMessage = HttpContext.Features.Get<IExceptionHandlerPathFeature>()?.Error.Message;
            else
                errMessage = "Возникла неизвестная ошибка";

            return View(new ErrorViewModel
            {
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                ExceptionMessage = errMessage
            });
        }
    }
}

WebUi/Views/Calculate/CurrentResult.cshtml
@{
    Layout = "_Layout";
}
@model List<CurrentResult>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CurrentResult</title>
</head>
<body>

    <div class="row">
        <div class="col-md-6">
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th>
                            Вид услуги
                        </th>
                        <th>
                            Объем услуг
                        </th>
                        <th>
                            Норматив
                        </th>
                        <th>
                            Тариф
                        </th>
                        <th>
                            Стоимость
                        </th>
                    </tr>
                    @foreach (var m in Model)
                    {
                        <tr>
                            <td>@m.ServiceTypeName</td>
                            <td>@m.VolumeOfServices @m.Units</td>
                            <td>@m.Normative @m.Units</td>
                            <td>@m.Rate</td>
                            <td>@m.Cost</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</body>
</html>

WebUi/Views/Calculation/CurrentResult.cshtml
@{
    Layout = "_Layout";
}
@model List<CurrentResult>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CurrentResult</title>
</head>
<body>
    @using (Html.BeginForm("PutValues", "Calculation", HttpMethod.Get))
    {
        <div class="w-50 container-fluid justify-content-center align-items-center p-0">
        <div>
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th>Вид услуги</th>
                        <th>Объем услуг</th>
                        <th>Норматив</th>
                            <th class="text-nowrap">Тариф, &#8381;</th>
                            <th class ="text-nowrap">Стоимость, &#8381;</th>
                    </tr>
                    @foreach (var m in Model)
                    {
                        <tr>
                            <td>@m.ServiceTypeName</td>
                            <td class="text-nowrap align-middle">@m.VolumeOfServices @m.Units</td>
                            @if(m.ServiceTypeName == "ГВС Тепловая Энергия"){
                              <td class="text-nowrap align-middle">@m.Normative @m.Units на М&#179;</td>
                            }
                            @if (m.ServiceTypeName != "ГВС Тепловая Энергия")
                            {
                               <td class="text-nowrap align-middle">@m.Normative @m.Units</td>
                            }
                            <td class="align-middle">@m.Rate</td>
                            <td class="align-middle">@m.Cost</td>
                        </tr>
                    }
                        <tr>
                            <td>СУММА</td>
                            <td>-</td>
                            <td>-</td>
                            <td>-</td>
                            <td>@ViewBag.CommonCost</td>
                        </tr>
                    
                </tbody>
            </table>
                    <p><input type="submit" value="Продолжить" class="btn-primary"></p>
        </div>
    </div>
    }
</body>
</html>

WebUi/Views/Calculation/PutValues.cshtml
@{
    Layout = "_Layout";
}

@model RequestData
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport"  />

</head>
<body>
    <div >
    @using (Html.BeginForm("CurrentResult", "Calculation", HttpMethod.Post))
    {
            <div class="w-50 container-fluid justify-content-center align-items-center p-0">
            <table class="table table-striped">
            <tbody>
                <tr>
                    <th>Парметр</th>
                    <th>Значение</th>
                </tr>
                    <tr>
                        <th>Количество <br> проживающих</th>
                        <th>
                            @Html.TextBoxFor(p => p.ResidentsCount, new { @class = "form-control" })
                            <span asp-validation-for="ResidentsCount" class="text-danger" />
                        </th>
                    </tr>
                    <tr><th>ХВС</th><th>@Html.TextBoxFor(p => p.ColdWaterMeterValues, new { @class = "form-control" })
                                <span asp-validation-for="ColdWaterMeterValues" class="text-danger" /></th></tr>
                    <tr><th>ГВС</th><th>@Html.TextBoxFor(p => p.HotWaterMeterValue, new { @class = "form-control" })
                                <span asp-validation-for="HotWaterMeterValue" class="text-danger" /></th></tr>
                    <tr><th>ЭЭ</th><th>@Html.TextBoxFor(p => p.ElectroEnergyCommonMeterValue, new { @class = "form-control" })
                                <span asp-validation-for="ElectroEnergyCommonMeterValue" class="text-danger" /></th></tr>
                    <tr><th>ЭЭ День</th><th>@Html.TextBoxFor(p => p.ElectroEnergyDayMeterValue, new { @class = "form-control" })
                                <span asp-validation-for="ElectroEnergyDayMeterValue" class="text-danger" /></th></tr>
                    <tr><th>ЭЭ Ночь</th><th>@Html.TextBoxFor(p => p.ElectroEnergyNightMeterValue, new { @class = "form-control" })
                                <span asp-validation-for="ElectroEnergyNightMeterValue" class="text-danger" /></th></tr>
            </tbody>
        </table>
            <p><input type="submit" value="Рассчитать" class="btn-primary"></p>
        </div>
    }
    </div>
</body>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.1.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>
</html>

WebUi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebUi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebUi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebUi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>